<?php

namespace ContainerY7Us3iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XOE48jEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XOE48jE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XOE48jE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'maternalMortalityRepository' => ['privates', 'App\\Repository\\MaternalMortalityRepository', 'getMaternalMortalityRepositoryService', true],
            'overcrowdedRepository' => ['privates', 'App\\Repository\\OvercrowdingRepository', 'getOvercrowdingRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'maternalMortalityRepository' => 'App\\Repository\\MaternalMortalityRepository',
            'overcrowdedRepository' => 'App\\Repository\\OvercrowdingRepository',
        ]);
    }
}
