<?php

namespace ContainerY7Us3iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOvercrowdedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OvercrowdedController' shared autowired service.
     *
     * @return \App\Controller\OvercrowdedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OvercrowdedController.php';

        $container->services['App\\Controller\\OvercrowdedController'] = $instance = new \App\Controller\OvercrowdedController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\OvercrowdedController', $container));

        return $instance;
    }
}
