<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIGVRlc\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIGVRlc/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHIGVRlc.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHIGVRlc\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerHIGVRlc\App_KernelTestDebugContainer([
    'container.build_hash' => 'HIGVRlc',
    'container.build_id' => '68e7ddd9',
    'container.build_time' => 1684505458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIGVRlc');
