<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7Us3iq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7Us3iq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY7Us3iq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY7Us3iq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY7Us3iq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y7Us3iq',
    'container.build_id' => '0a3c129a',
    'container.build_time' => 1685722761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7Us3iq');
