<?php

namespace ContainerJj2gEzB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYfiFgzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TYfiFgz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TYfiFgz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'overcrowdedRepository' => ['privates', 'App\\Repository\\OvercrowdingRepository', 'getOvercrowdingRepositoryService', true],
        ], [
            'overcrowdedRepository' => 'App\\Repository\\OvercrowdingRepository',
        ]);
    }
}
